sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t manureichel/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true manureichel/frontend npm run test
