sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t manureichel/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true manureichel/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: frontend
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-378185288543"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
